
name: Mac
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_macos_intel:
    if: github.repository_owner == 'myridia'
    runs-on: macos-13
    steps:
       - name: install nappgui 
         run: |
          git clone --depth 1 https://github.com/frang75/nappgui_src.git
          cd nappgui_src
          cmake --version 
          cmake -G Xcode -S . -B build -DNAPPGUI_DEMO=NO
          cmake --build build --config Release -j 4
          sudo cmake --install build --config Release --prefix /usr/local/nappgui
          
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: build hello_c_gui
         run: |
           cmake -G Xcode -S . -B build -DCMAKE_INSTALL_PREFIX=/usr/local/nappgui
           cmake --build build --config Release
           ls  build/Release/bin/
           ls build/Release/bin/hello_c_nappgui.app
           cd build/Release/bin/
           hdiutil create -volname "hello_c_nappgui" -srcfolder "hello_c_nappgui.app" -ov -format UDZO "hello_c_nappgui.dmg"
           #tar -czf hello_c_nappgui.app.tar.gz build/Release/bin/ ./hello_c_nappgui.app

       #- name: Upload Macos Intel Binary to release
       #  uses: svenstaro/upload-release-action@v2
       #  with:
       #   repo_token: ${{ secrets.GITHUB_TOKEN }}
       #   file: 'hello_c_nappgui.app.tar.gz'
       #   tag: ${{ github.ref }}
       #   overwrite: true
       #   file_glob: true   
