name: Windows

on:
  push:
    branches: ["main"]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build_linux_windows:
    if: github.repository_owner == 'myridia'
    runs-on: windows-latest
    steps:
      - name: build windows
        run: |
          cmake -S . -B build -DNAPPGUI_DEMO=NO
          cmake --build build --config Release -j 4
          cmake --install build --config Release --prefix C:/nappgui

        
    

        


        


 
     
