name: build_indows

on:
  push:
    branches: ["main"]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build_linux_windows:
    if: github.repository_owner == 'myridia'
    runs-on: windows-latest
    steps:
      - name: download nappgui_rs
        run: |
          git clone --depth 1 https://github.com/frang75/nappgui_src.git
          cd nappgui_src
      - name: build and install nappgui
        run: |
          cmake -S . -B build -DNAPPGUI_DEMO=NO
          cmake --build build --config Release -j 4
          cmake --install build --config Release --prefix C:/nappgui

        
    

        


        


 
     
