name: Build Release

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build:
    if: github.repository_owner == 'myridiax'
    runs-on: ubuntu-22.04  
    steps:
      - name: install dependencies
        run: |
         sudo apt-get install build-essential git cmake -y
         sudo apt-get install libgtk-3-dev libgtk-4-dev libcurl4-gnutls-dev -y
         sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev  -y
         

      - name: install nappgui 
        run: |
          git clone --depth 1 https://github.com/frang75/nappgui_src.git
          cd nappgui_src
          cmake -S . -B build -DNAPPGUI_DEMO=NO -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j 4
          sudo cmake --install build --config Release --prefix /usr/local/nappgui
       
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build hello_c_gui
        run: |
         cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/nappgui
         cmake --build build
        

        
      - name: upload binary 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/Release/bin/hello_c_nappgui'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true


          
