
name: Mac
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_macos_intel:
    if: github.repository_owner == 'myridia'
    runs-on: macos-13
    steps:
       - name: install nappgui 
         run: |
          git clone --depth 1 https://github.com/frang75/nappgui_src.git
          cd nappgui_src
          cmake -G Xcode -S . -B build -DNAPPGUI_DEMO=NO
          cmake --build build --config Release -j 4
          cmake --install build --config Release --prefix /usr/local/nappgu
  

      #- name: Upload Macos Intel Binary to release
      #  uses: svenstaro/upload-release-action@v2
      #  with:
      #    repo_token: ${{ secrets.GITHUB_TOKEN }}
      #    file: 'dist/uaf_macos'
      #    tag: ${{ github.ref }}
      #    overwrite: true
      #    file_glob: true   
